exclude_paths:
  - tmp
  - vendor

detectors:
  ControlParameter:
    exclude:
      - "Tocer::CLI::Actions::Label#call"
      - "Tocer::CLI::Actions::Pattern#call"
      - "Tocer::CLI::Actions::Root#call"
  LongParameterList:
    enabled: false
  TooManyStatements:
    exclude:
      - "Tocer::CLI::Shell#cli"
