# frozen_string_literal: true

require "tocer/identity"
require "tocer/configuration"
require "tocer/elements/comment_block"
require "tocer/parsers/header"
require "tocer/transformers/link"
require "tocer/transformers/text"
require "tocer/transformers/finder"
require "tocer/builder"
require "tocer/writer"
require "tocer/runner"
require "tocer/cli/configuration/content"
require "tocer/cli/configuration/loader"
require "tocer/cli/parsers"
require "tocer/cli/parsers/build"
